repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      types: [python]
#-   repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: stable
#    hooks:
#    - id: flake8
